apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-app-deploy
  # namespace: blog-app-ns
  labels:
    app: blog-app
spec:
  selector:
    matchLabels:
      app: blog-app
  replicas: 2
  template:
    metadata:
      labels:
        app: blog-app
    spec:
      containers:
      - name: blog-container
        image: 628251107431.dkr.ecr.us-east-2.amazonaws.com/blog-app
        ports:
         - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: blog-app-svc
  # namespace: blog-app-ns
  labels:
    app: blog-app
spec:
  selector:
    app: blog-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer