apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-app-deploy
  # namespace: blog-app-ns
  labels:
    app: blog-app
spec:
  selector:
    matchLabels:
      app: blog-app
  replicas: 2
  template:
    metadata:
      labels:
        app: blog-app
    spec:
      containers:
      - name: blog-container
        image: 628251107431.dkr.ecr.us-east-2.amazonaws.com/blog-app:latest
        imagePullPolicy: Always
        ports:
         - containerPort: 80